=== eclipse-archived/smarthome/tools/binding-docu-generator/src/main/xsd/config-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
           targetNamespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0">

    <xs:element name="config-descriptions">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="config-description" type="config-description:configDescription"
                            minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="config-description" type="config-description:configDescription"/>

    <xs:simpleType name="idRestrictionPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="uriRestrictionPattern">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z0-9\-_]+(:[A-Za-z0-9\-_]+){1,2}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="configDescription">
        <xs:sequence>
            <xs:element name="parameter-group" type="config-description:parameterGroup"
                        minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="parameter" type="config-description:parameter"
                        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="uri"
                      type="config-description:uriRestrictionPattern" use="optional"/>
    </xs:complexType>

    <xs:complexType name="parameter">
        <xs:all>
            <xs:element name="context" type="xs:string" minOccurs="0"/>
            <!-- deprecated element "required" -->
            <xs:element name="required" type="xs:boolean" default="false"
                        minOccurs="0"/>
            <xs:element name="default" type="xs:string" minOccurs="0"/>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="options" type="config-description:optionsType"
                        minOccurs="0"/>
            <xs:element name="limitToOptions" type="xs:boolean"
                        minOccurs="0"/>
            <xs:element name="filter" type="config-description:filterType"
                        minOccurs="0"/>
            <xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
            <xs:element name="multipleLimit" type="xs:integer" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="config-description:parameterType"
                      use="required"/>
        <xs:attribute name="groupName" type="xs:string"/>
        <xs:attribute name="min" type="xs:decimal"/>
        <xs:attribute name="max" type="xs:decimal"/>
        <xs:attribute name="step" type="xs:decimal"/>
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="readOnly" type="xs:boolean"/>
        <xs:attribute name="multiple" type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="parameterGroup">
        <xs:all>
            <xs:element name="label" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="context" type="xs:string" minOccurs="0"/>
            <xs:element name="advanced" type="xs:boolean" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="optionsType">
        <xs:sequence>
            <xs:element name="option" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="value" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="filterType">
        <xs:sequence>
            <xs:element name="criteria" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="parameterType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="decimal"/>
            <xs:enumeration value="boolean"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="configDescriptionRef">
        <xs:attribute name="uri"
                      type="config-description:uriRestrictionPattern" use="required"/>
    </xs:complexType>

</xs:schema>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/ESH-INF/config/homie-channel-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0 http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="mqtt:homie_channel">
		<parameter name="unit" type="text">
			<label>Unit</label>
			<description>The channels unit</description>
			<default></default>
		</parameter>
		<parameter name="name" type="text">
			<label>Name</label>
			<description>The channel name</description>
			<default></default>
		</parameter>
		<parameter name="settable" type="text">
			<label>Settable</label>
			<description>Is this channel writable?</description>
			<default>true</default>
		</parameter>
		<parameter name="retained" type="text">
			<label>Retained</label>
			<description>If set to false, the resulting channel will be a trigger channel (stateless), useful for non-permanent events. This flag corresponds to the retained option for MQTT publish.</description>
			<default>true</default>
		</parameter>
		<parameter name="format" type="text">
			<label>Format</label>
			<description>The output format.</description>
			<default></default>
		</parameter>
		<parameter name="datatype" type="text">
			<label>Data Type</label>
			<description>The data type of this channel.</description>
			<default>unknown</default>
			<options>
				<option value="integer_">Integer</option>
				<option value="float_">Float</option>
				<option value="boolean_">Boolean</option>
				<option value="string_">String</option>
				<option value="enum_">Enumeration</option>
				<option value="color_">Colour</option>
			</options>
		</parameter>
	</config-description>
</config-description:config-descriptions>

=== eclipse-archived/smarthome/extensions/ui/org.eclipse.smarthome.ui.basic/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0
        http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

	<config-description uri="ui:basic">
		<parameter name="iconType" type="text" required="true">
			<label>Icon Format</label>
			<description>Defines whether bitmap or vector icons are used by the UI.</description>
			<options>
				<option value="png">Bitmap</option>
				<option value="svg">Vector</option>
			</options>
		</parameter>
		<parameter name="enableIcons" type="text" required="true">
			<label>Enable Icons</label>
			<description>Defines whether UI renders icons for the widgets or not.</description>
			<options>
				<option value="true">Enable</option>
				<option value="false">Disable</option>
			</options>
		</parameter>
		<parameter name="defaultSitemap" type="text" required="false">
			<label>Default Sitemap</label>
			<description>The sitemap to show if no parameter is passed.</description>
		</parameter>
	</config-description>

</config-description:config-descriptions>
