=== eclipse-archived/smarthome/bundles/config/org.eclipse.smarthome.config.xml/config-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
        xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
        targetNamespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0">

	<xs:element name="config-descriptions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="config-description" type="config-description:configDescription" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="config-description" type="config-description:configDescription"/>

	<xs:complexType name="configDescription">
		<xs:sequence>
			<xs:element name="parameter" type="config-description:parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="uri" type="xs:string" use="optional"/>
	</xs:complexType>

	<xs:complexType name="parameter">
		<xs:all>
			<xs:element name="context" type="xs:string" minOccurs="0"/>
			<xs:element name="required" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="default" type="xs:string" minOccurs="0"/>
			<xs:element name="label" type="xs:string" minOccurs="0"/>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="config-description:parameterType" use="required"/>
	</xs:complexType>

	<xs:simpleType name="parameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="text"/>
			<xs:enumeration value="integer"/>
			<xs:enumeration value="decimal"/>
			<xs:enumeration value="boolean"/>
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="configDescriptionRef">
        <xs:attribute name="uri" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== eclipse-archived/smarthome/bundles/core/org.eclipse.smarthome.core.voice/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0 http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

    <config-description uri="system:voice">
        <parameter name="defaultTTS" type="text" required="false">
            <label>Default Text-to-Speech</label>
            <description>The default text-to-speech service to use if no other is specified.</description>
        </parameter>
        <parameter name="defaultSTT" type="text" required="false">
            <label>Default Speech-to-Text</label>
            <description>The default speech-to-text service to use if no other is specified.</description>
        </parameter>
        <parameter name="defaultVoice" type="text" required="false">
            <label>Default Voice</label>
            <description>The default voice to use if no specific TTS service or voice is specified.</description>
        </parameter>
        <parameter name="defaultHLI" type="text" required="false">
            <label>Default Human Language Interpreter</label>
            <description>The default human language interpreter to use if no other is specified.</description>
        </parameter>
        <parameter name="defaultKS" type="text" required="false">
            <label>Default Keyword Spotter</label>
            <description>The default keyword spotting service to use if no other is specified.</description>
        </parameter>
        <parameter name="keyword" type="text" required="false">
            <label>Magic Word</label>
            <description>The magic word to spot before initiating a dialog.</description>
        </parameter>
    </config-description>

</config-description:config-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config-description:config-descriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/config-description/v1.0.0 http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd">

    <config-description uri="thing-type:lifx:light">
        <parameter name="deviceId" type="text" required="true">
            <label>LIFX device ID</label>
        </parameter>
        <parameter name="fadetime" type="integer" required="false">
            <label>Fade time</label>
            <description>The time to fade to the new color value (in ms).</description>
            <default>300</default>
        </parameter>
    </config-description>

    <config-description uri="channel-type:lifx:brightness">
        <parameter name="powerOnBrightness" type="integer" min="0" max="100" required="false" unit="%">
            <label>Power on brightness</label>
            <description>Brightness level used when switching on the light. Use empty value to leave brightness as is.</description>
        </parameter>
    </config-description>

</config-description:config-descriptions>
