=== eclipse-archived/smarthome/bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:thing-description="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
        targetNamespace="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0">

    <xs:import namespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
            schemaLocation="http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd"/>

    <xs:element name="thing-descriptions">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="thing-type" type="thing-description:thingType"/>
                <xs:element name="bridge-type" type="thing-description:bridgeType"/>
                <xs:element name="channel-type" type="thing-description:channelType"/>
            </xs:choice>
            <xs:attribute name="bindingId" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="thingType">
        <xs:sequence>
            <xs:element name="supported-bridge-type-refs" type="thing-description:supportedBridgeTypeRefs" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="channels" type="thing-description:channels" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="supportedBridgeTypeRefs">
        <xs:sequence>
            <xs:element name="bridge-type-ref" type="thing-description:bridgeTypeRef" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeTypeRef">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="channels">
        <xs:sequence>
            <xs:element name="channel" type="thing-description:channel" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeType">
        <xs:complexContent>
            <xs:extension base="thing-description:thingType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="channel">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="typeId" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="channelType">
        <xs:sequence>
            <xs:element name="item-type" type="xs:string"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.tradfri/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="tradfri"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<bridge-type id="gateway">
		<label>TRÅDFRI Gateway</label>
		<description>IKEA TRÅDFRI IP Gateway</description>

		<config-description-ref uri="bridge-type:tradfri:gateway" />
	</bridge-type>

	<!-- thing types for devices -->
	<!-- their IDs refer to the Zigbee Lightlink device ids (see chapter 2.2 in https://www.nxp.com/documents/user_manual/JN-UG-3091.pdf) -->
	<thing-type id="0010">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>On/Off Plug</label>
		<description>A plug that can be switched on and off.</description>

		<channels>
			<channel id="power" typeId="system.power" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<thing-type id="0100">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>Dimmable Light</label>
		<description>A light that has continuous brightness control.</description>

		<channels>
			<channel id="brightness" typeId="brightness" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<thing-type id="0220">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>Color Temperature Light</label>
		<description>A dimmable light that supports different color temperature settings.</description>

		<channels>
			<channel id="brightness" typeId="brightness" />
			<channel id="color_temperature" typeId="color_temperature" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<thing-type id="0210">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>Color Light</label>
		<description>A dimmable light that supports full colors and color temperature settings.</description>

		<channels>
			<channel id="color_temperature" typeId="color_temperature" />
			<channel id="color" typeId="color" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<thing-type id="0107">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>Occupancy Sensor</label>
		<description>This represents the motion sensor capable of reporting the battery level.</description>

		<channels>
			<channel id="battery_level" typeId="system.battery-level" />
			<channel id="battery_low" typeId="system.low-battery" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<thing-type id="0820" listed="false">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>Non-Colour Controller</label>
		<description>This represents the wireless dimmer sensor capable of reporting the battery level.</description>

		<channels>
			<channel id="battery_level" typeId="system.battery-level" />
			<channel id="battery_low" typeId="system.low-battery" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<thing-type id="0830">
		<supported-bridge-type-refs>
			<bridge-type-ref id="gateway" />
		</supported-bridge-type-refs>

		<label>Non-Colour Scene Controller</label>
		<description>This represents the remote control capable of reporting the battery level.</description>

		<channels>
			<channel id="battery_level" typeId="system.battery-level" />
			<channel id="battery_low" typeId="system.low-battery" />
		</channels>

		<representation-property>id</representation-property>

		<config-description-ref uri="thing-type:tradfri:device" />
	</thing-type>

	<channel-type id="brightness">
		<item-type>Dimmer</item-type>
		<label>Brightness</label>
		<description>Control the brightness and switch the light on and off.</description>
		<category>DimmableLight</category>
		<tags>
			<tag>Lighting</tag>
		</tags>
	</channel-type>

	<channel-type id="color_temperature">
		<item-type>Dimmer</item-type>
		<label>Color Temperature</label>
		<description>Control the color temperature of the light.</description>
		<category>ColorLight</category>
	</channel-type>

	<channel-type id="color">
		<item-type>Color</item-type>
		<label>Color</label>
		<description>Control the color of the light.</description>
		<category>ColorLight</category>
	</channel-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.ble.yeelightblue/ESH-INF/thing/yeelight_blue2.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="ble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- Sample Thing Type -->
	<thing-type id="yeelight_blue2" listed="false">
		<label>YeeLightBlue II Light Bulb</label>
		<description></description>

		<channels>
			<channel id="switch" typeId="switch">
			</channel>

			<channel id="brightness" typeId="brightness">
			</channel>

			<channel id="color" typeId="color">
			</channel>

			<channel id="rssi" typeId="rssi">
			</channel>
		</channels>

		<properties>
			<property name="bleFilter">NAME=Yeelight Blue II</property>
		</properties>

		<config-description>
			<parameter name="ble_address" type="text">
				<label>BLE Address</label>
				<description>Bluetooth address in XX:XX:XX:XX:XX:XX format</description>
			</parameter>
		</config-description>

	</thing-type>


	<!-- RSSI Channel -->
	<channel-type id="rssi">
		<item-type>Number</item-type>
		<label>RSSI</label>
		<description>The RSSI channel provides the current receive signal strength of the device</description>
		<category>QualityOfService</category>
	</channel-type>

	<!-- Color Channel -->
	<channel-type id="color">
		<item-type>Color</item-type>
		<label>Color</label>
		<description>The color channel allows to control the color of a light.
            It is also possible to dim values and switch the light on and off.
        </description>
		<category>ColorLight</category>
	</channel-type>

	<!-- Brightness Channel -->
	<channel-type id="brightness">
		<item-type>Dimmer</item-type>
		<label>Brightness</label>
		<description>The brightness channel allows to control the brightness of a light.
            It is also possible to switch the light on and off.
        </description>
		<category>DimmableLight</category>
	</channel-type>

	<!-- Switch Channel -->
	<channel-type id="switch">
		<item-type>Switch</item-type>
		<label>Switch</label>
		<description>Switch the light on and off</description>
		<category>Light</category>
	</channel-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/tools/archetype/binding/src/main/resources/archetype-resources/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="${bindingId}"
						  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
						  xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
						  xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- Sample Thing Type -->
	<thing-type id="sample">
		<label>${bindingIdCamelCase} Binding Thing</label>
		<description>Sample thing for ${bindingIdCamelCase} Binding</description>

		<channels>
			<channel id="channel1" typeId="sample-channel"/>
		</channels>
	</thing-type>

	<!-- Sample Channel Type -->
	<channel-type id="sample-channel">
		<item-type>${bindingId}Item</item-type>
		<label>${bindingIdCamelCase} Binding Channel</label>
		<description>Sample channel for ${bindingIdCamelCase} Binding</description>
	</channel-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.digitalstrom/ESH-INF/thing/dssBridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="digitalstrom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd"
>

    <!--DigitalStrom Bridge -->
    <bridge-type id="dssBridge">
        <label>@text/DSS_BRIDGE_LABEL</label>
        <description>@text/DSS_BRIDGE_DESC</description>
        <channels>
            <channel typeId="totalActivePower" id="totalActivePower" />
            <channel typeId="totalElectricMeter" id="totalElectricMeter" />
        </channels>
        <properties>
            <property name="serverCert"></property>
        </properties>
        <config-description-ref uri="binding:digitalstrom:dssBridge" />
    </bridge-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/ZLL_Light.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- Generic ZigBee LightLink Bulb -->
    <thing-type id="ZLL_Light">
        <supported-bridge-type-refs>
            <bridge-type-ref id="bridge" />
        </supported-bridge-type-refs>

        <label>ZigBee LightLink Bulb</label>
        <description>This is a generic ZigBee LightLink Bulb</description>

        <channels>
            <channel id="brightness" typeId="brightness" />
        </channels>

        <config-description>
            <parameter name="lightId" type="text">
                <label>Light ID</label>
                <description>The light identifier identifies one certain light.</description>
                <required>true</required>
            </parameter>
        </config-description>
    </thing-type>
</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/ColorLight.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- Generic thing for color lights (ZigBee Device ID: 0x0200) -->
	<thing-type id="color_light">
		<supported-bridge-type-refs>
			<bridge-type-ref id="bridge" />
		</supported-bridge-type-refs>

		<label>Hue supported color lights</label>
		<description>Supports all color lights</description>

		<channels>
			<channel id="color" typeId="color" />
			<channel id="brightness" typeId="brightness" />
			<channel id="alert" typeId="alert" />
			<channel id="effect" typeId="effect" />
		</channels>

		<config-description>
			<parameter name="lightId" type="text">
				<label>Light ID</label>
				<description>The light identifier identifies one certain hue light.</description>
				<required>true</required>
			</parameter>
		</config-description>
	</thing-type>
</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/CONNECTAMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="sonos" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- Amplifier CONNECT:AMP Thing Type -->
	<thing-type id="CONNECTAMP" listed="false">
		<!-- Label without column (:) because of device pairing name restrictions -->
		<label>CONNECT AMP</label>
		<description>Represents SONOS CONNECT:AMP amplifier</description>

		<channels>
			<channel id="add" typeId="add" />
			<channel id="alarm" typeId="alarm" />
			<channel id="alarmproperties" typeId="alarmproperties" />
			<channel id="alarmrunning" typeId="alarmrunning" />
			<channel id="control" typeId="control" />
			<channel id="currentalbum" typeId="currentalbum" />
			<channel id="currentartist" typeId="currentartist" />
			<channel id="currenttitle" typeId="currenttitle" />
			<channel id="currenttrack" typeId="currenttrack" />
			<channel id="shuffle" typeId="shuffle" />
			<channel id="repeat" typeId="repeat" />
			<channel id="favorite" typeId="favorite" />
			<channel id="led" typeId="led" />
			<channel id="localcoordinator" typeId="localcoordinator" />
			<channel id="mute" typeId="mute" />
			<channel id="notificationsound" typeId="notificationsound" />
			<channel id="notificationvolume" typeId="notificationvolume" />
			<channel id="playlist" typeId="playlist" />
			<channel id="playqueue" typeId="playqueue" />
			<channel id="playtrack" typeId="playtrack" />
			<channel id="playuri" typeId="playuri" />
			<channel id="publicaddress" typeId="publicaddress" />
			<channel id="radio" typeId="radio" />
			<channel id="remove" typeId="remove" />
			<channel id="restore" typeId="restore" />
			<channel id="restoreall" typeId="restoreall" />
			<channel id="save" typeId="save" />
			<channel id="saveall" typeId="saveall" />
			<channel id="snooze" typeId="snooze" />
			<channel id="standalone" typeId="standalone" />
			<channel id="state" typeId="state" />
			<channel id="stop" typeId="stop" />
			<channel id="volume" typeId="volume" />
			<channel id="zonegroup" typeId="zonegroup" />
			<channel id="zonegroupid" typeId="zonegroupid" />
			<channel id="zonename" typeId="zonename" />
			<channel id="coordinator" typeId="coordinator" />
			<!-- Extended SONOS channels (PLAY5, CONNECT & CONNECT:AMP only) -->
			<channel id="linein" typeId="linein" />
			<channel id="playlinein" typeId="playlinein" />
			<channel id="sleeptimer" typeId="sleeptimer" />
			<channel id="currenttransporturi" typeId="currenttransporturi" />
			<channel id="currenttrackuri" typeId="currenttrackuri" />
		</channels>

		<properties>
			<property name="vendor">SONOS</property>
			<property name="modelId">CONNECT:AMP</property>
		</properties>

		<config-description>
			<parameter name="udn" type="text">
				<label>Unique Device Name</label>
				<description>The UDN identifies the Zone Player.</description>
				<required>true</required>
			</parameter>

			<parameter name="refresh" type="integer">
				<label>Refresh interval</label>
				<description>Specifies the refresh interval in seconds</description>
				<default>60</default>
			</parameter>
		</config-description>
	</thing-type>
</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.bluetooth/ESH-INF/thing/bridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="bluetooth"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <bridge-type id="adapter">
        <label>Bluetooth Adapter</label>
        <description>Bluetooth Adapter</description>
        <channels>
            <channel id="ready" typeId="ready"/>
            <channel id="powered" typeId="powered"/>
            <channel id="powered-control" typeId="powered-control"/>
            <channel id="discovering" typeId="discovering"/>
            <channel id="discovering-control" typeId="discovering-control"/>
            <channel id="last-updated" typeId="last-updated"/>
        </channels>
    </bridge-type>

</thing:thing-descriptions>
