=== eclipse-archived/smarthome/bundles/core/org.eclipse.smarthome.core.thing.xml/thing-description-1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:thing-description="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
        xmlns:config-description="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
        targetNamespace="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0">

    <xs:import namespace="http://eclipse.org/smarthome/schemas/config-description/v1.0.0"
            schemaLocation="http://eclipse.org/smarthome/schemas/config-description-1.0.0.xsd"/>

    <xs:element name="thing-descriptions">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="thing-type" type="thing-description:thingType"/>
                <xs:element name="bridge-type" type="thing-description:bridgeType"/>
                <xs:element name="channel-type" type="thing-description:channelType"/>
            </xs:choice>
            <xs:attribute name="bindingId" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="thingType">
        <xs:sequence>
            <xs:element name="supported-bridge-type-refs" type="thing-description:supportedBridgeTypeRefs" minOccurs="0"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="channels" type="thing-description:channels" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="supportedBridgeTypeRefs">
        <xs:sequence>
            <xs:element name="bridge-type-ref" type="thing-description:bridgeTypeRef" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeTypeRef">
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="channels">
        <xs:sequence>
            <xs:element name="channel" type="thing-description:channel" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bridgeType">
        <xs:complexContent>
            <xs:extension base="thing-description:thingType"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="channel">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="typeId" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="channelType">
        <xs:sequence>
            <xs:element name="item-type" type="xs:string"/>
            <xs:element name="label" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:choice minOccurs="0">
                <xs:element name="config-description" type="config-description:configDescription"/>
                <xs:element name="config-description-ref" type="config-description:configDescriptionRef"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.lifx/ESH-INF/thing/thing-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="lifx" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
    xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- LIFX Light -->
    <thing-type id="light">
        <label>LIFX Light</label>

        <channels>
            <channel id="color" typeId="color" />
        </channels>

        <config-description>
            <parameter name="deviceId" type="text" required="true">
                <label>LIFX device ID</label>
            </parameter>
        </config-description>
        
    </thing-type>

    <!-- Color Channel -->
    <channel-type id="color">
        <item-type>Color</item-type>
        <label>Color</label>
        <description>Selects the color of the light</description>
        <category>ColorLight</category>
    </channel-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.hue/ESH-INF/thing/DimmableLight.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="hue"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- Generic thing for dimmable lights (ZigBee Device ID: 0x0100) -->
	<thing-type id="0100">
		<supported-bridge-type-refs>
			<bridge-type-ref id="bridge" />
		</supported-bridge-type-refs>

		<label>Dimmable Light</label>
		<description>A dimmable light.</description>

		<channels>
			<channel id="brightness" typeId="brightness" />
			<channel id="alert" typeId="alert" />
		</channels>

        <representation-property>uniqueId</representation-property>

		<config-description>
			<parameter name="lightId" type="text">
				<label>Light ID</label>
				<description>The light identifier identifies one certain hue light.</description>
				<required>true</required>
			</parameter>
		</config-description>
	</thing-type>
</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.sonos/ESH-INF/thing/channels.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="sonos"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<!-- Channels common for all SONOS devices -->
	<channel-type id="add" advanced="true">
		<item-type>String</item-type>
		<label>Add</label>
		<description>Add the given Zone Player to the group of this Zone Player</description>
	</channel-type>

	<channel-type id="alarm" advanced="true">
		<item-type>Switch</item-type>
		<label>Set Alarm</label>
		<description>Set the first occurring alarm either ON or OFF. Alarms first have to be defined through the Sonos Controller app</description>
	</channel-type>

	<channel-type id="alarmproperties" advanced="true">
		<item-type>String</item-type>
		<label>Alarm Properties</label>
		<description>Properties of the alarm currently running</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="alarmrunning" advanced="true">
		<item-type>Switch</item-type>
		<label>Alarm is running</label>
		<description>Set to ON if the alarm was triggered</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="clearqueue" advanced="true">
		<item-type>Switch</item-type>
		<label>Clear Queue</label>
		<description>Suppress all songs from the current queue</description>
	</channel-type>

	<channel-type id="coordinator" advanced="true">
		<item-type>String</item-type>
		<label>Coordinator</label>
		<description>UDN of the coordinator for the current group</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="currentalbum">
		<item-type>String</item-type>
		<label>Current Album</label>
		<description>Name of the album currently playing</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="currentalbumart">
		<item-type>Image</item-type>
		<label>Current Album Cover Art</label>
		<description>Cover art of the album currently playing</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="currentalbumarturl" advanced="true">
		<item-type>String</item-type>
		<label>Current Album Cover Art URL</label>
		<description>Cover art URL of the album currently playing</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="currenttrack" advanced="true">
		<item-type>String</item-type>
		<label>Current Track</label>
		<description>Name of the current track or radio station currently playing</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="currenttrackuri" advanced="true">
		<item-type>String</item-type>
		<label>Current track URI</label>
		<description>URI of the current track</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="currenttransporturi" advanced="true">
		<item-type>String</item-type>
		<label>Current AV transport URI</label>
		<description>URI of the current AV transport</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="favorite" advanced="true">
		<item-type>String</item-type>
		<label>Favorite</label>
		<description>Play the given favorite entry. The favorite entry has to be predefined in the Sonos Controller app</description>
	</channel-type>

	<channel-type id="led" advanced="true">
		<item-type>Switch</item-type>
		<label>Led</label>
		<description>Set or get the status of the white led on the front of the Zone Player</description>
	</channel-type>

	<channel-type id="localcoordinator" advanced="true">
		<item-type>Switch</item-type>
		<label>Local Coordinator</label>
		<description>Indicator set to ON if this Zone Player is the Zone Group Coordinator</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="nightmode" advanced="true">
		<item-type>Switch</item-type>
		<label>Night Mode</label>
		<description>Enable or disable the night mode feature</description>
	</channel-type>

	<channel-type id="notificationsound" advanced="true">
		<item-type>String</item-type>
		<label>Notification Sound</label>
		<description>Play a notification sound by a given URI</description>
	</channel-type>

	<channel-type id="playlist" advanced="true">
		<item-type>String</item-type>
		<label>Play Playlist</label>
		<description>Play the given playlist. The playlist has to predefined in the Sonos Controller app</description>
	</channel-type>

	<channel-type id="playqueue" advanced="true">
		<item-type>Switch</item-type>
		<label>Play Queue</label>
		<description>Play the songs from the current queue</description>
	</channel-type>

	<channel-type id="playtrack" advanced="true">
		<item-type>Number</item-type>
		<label>Play Track</label>
		<description>Play the given track number from the current queue</description>
	</channel-type>

	<channel-type id="playuri" advanced="true">
		<item-type>String</item-type>
		<label>Play URI</label>
		<description>Play the given URI</description>
	</channel-type>

	<channel-type id="publicaddress" advanced="true">
		<item-type>Switch</item-type>
		<label>Public Address</label>
		<description>Put all Zone Players in one group, and stream audio from the line-in from the Zone Player that triggered the command</description>
	</channel-type>

	<channel-type id="radio" advanced="true">
		<item-type>String</item-type>
		<label>Radio</label>
		<description>Play the given radio station. The radio station has to be predefined in the Sonos Controller app</description>
	</channel-type>

	<channel-type id="remove" advanced="true">
		<item-type>String</item-type>
		<label>Remove</label>
		<description>Remove the given Zone Player from the group of this Zone Player</description>
	</channel-type>

	<channel-type id="repeat" advanced="true">
		<item-type>String</item-type>
		<label>Repeat</label>
		<description>Repeat track or queue playback</description>
	</channel-type>

	<channel-type id="restore" advanced="true">
		<item-type>Switch</item-type>
		<label>Restore</label>
		<description>Restore the state of the Zone Player</description>
	</channel-type>

	<channel-type id="restoreall" advanced="true">
		<item-type>Switch</item-type>
		<label>Restore All</label>
		<description>Restore the state of all the Zone Players</description>
	</channel-type>

	<channel-type id="save" advanced="true">
		<item-type>Switch</item-type>
		<label>Save</label>
		<description>Save the state of the Zone Player</description>
	</channel-type>

	<channel-type id="saveall" advanced="true">
		<item-type>Switch</item-type>
		<label>Save All</label>
		<description>Save the state of all the Zone Players</description>
	</channel-type>

	<channel-type id="shuffle" advanced="true">
		<item-type>Switch</item-type>
		<label>Shuffle</label>
		<description>Shuffle queue playback</description>
	</channel-type>

	<channel-type id="sleeptimer" advanced="true">
		<item-type>Number</item-type>
		<label>Sleep Timer</label>
		<description>Set/show the duration of the sleep timer in seconds</description>
		<state min="0" max="68399" step="1" readOnly="false" pattern="%d s" />
	</channel-type>

	<channel-type id="snooze" advanced="true">
		<item-type>Number</item-type>
		<label>Snooze</label>
		<description>Snooze the running alarm, if any, with the given number of minutes</description>
		<state readOnly="false" pattern="%d min" />
	</channel-type>

	<channel-type id="speechenhancement" advanced="true">
		<item-type>Switch</item-type>
		<label>Speech Enhancement </label>
		<description>Enable or disable the speech enhancement feature</description>
	</channel-type>

	<channel-type id="standalone" advanced="true">
		<item-type>Switch</item-type>
		<label>Stand Alone</label>
		<description>Make the Zone Player leave its group and become a standalone Zone Player</description>
	</channel-type>

	<!-- The Sonos State Type -->
	<channel-type id="state" advanced="true">
		<item-type>String</item-type>
		<label>State</label>
		<description>The State channel contains state of the Zone Player, e.g. PLAYING, STOPPED,...</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="stop" advanced="true">
		<item-type>Switch</item-type>
		<label>Stop</label>
		<description>Stop the Zone Player. ON if the player is stopped.</description>
	</channel-type>

	<channel-type id="tuneinstationid" advanced="true">
		<item-type>String</item-type>
		<label>TuneIn Station Id</label>
		<description>Provide the current TuneIn station id or play the TuneIn radio given by its station id</description>
	</channel-type>

	<channel-type id="zonegroupid" advanced="true">
		<item-type>String</item-type>
		<label>Zone Group ID</label>
		<description>Id of the Zone Group the Zone Player belongs to</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="zonename">
		<item-type>String</item-type>
		<label>Zone Name</label>
		<description>Name of the Zone Group associated to the Zone Player</description>
		<state readOnly="true" />
	</channel-type>

	<!-- Extended channels (for SONOS PLAY5, CONNECT & CONNECT:AMP only) -->
	<channel-type id="linein" advanced="true">
		<item-type>Switch</item-type>
		<label>Line-in connected</label>
		<description>Indicator set to ON when the line-in of the Zone Player is connected</description>
		<state readOnly="true" />
	</channel-type>

	<channel-type id="playlinein" advanced="true">
		<item-type>String</item-type>
		<label>Play Line-in</label>
		<description>Play the line-in of the the Zone Player corresponding to the given UIN</description>
	</channel-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/tools/binding-docu-generator/src/test/resources/testXMLs/thing-acOutletSimplePowerMetering.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="dect"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
                          xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

    <!-- DECT power outlet -->
    <thing-type id="acOutletSimplePowerMetering">
        <label>AC Outlet with Simple Power Metering</label>
        <description>An AC Outlet which can be turned on/off remotely and that has a simple Power Metering unit.
        </description>

        <!-- channels -->
        <channels>
            <channel id="onOffState" typeId="acSwitch"/>
            <channel id="powerMeteringEnergy" typeId="powerMeteringEnergy"/>
            <channel id="powerMeteringEnergyAtLastReset" typeId="powerMeteringEnergyAtLastReset"/>
            <channel id="powerMeteringTimeAtLastReset" typeId="powerMeteringTimeAtLastReset"/>
            <channel id="powerMeteringInstantaneousPower" typeId="powerMeteringInstantaneousPower"/>
            <channel id="powerMeteringAveragePower" typeId="powerMeteringAveragePower"/>
            <channel id="powerMeteringAveragePowerInterval" typeId="powerMeteringAveragePowerInterval"/>
            <channel id="powerMeteringVoltage" typeId="powerMeteringVoltage"/>
            <channel id="powerMeteringCurrent" typeId="powerMeteringCurrent"/>
            <channel id="powerMeteringFrequency" typeId="powerMeteringFrequency"/>
            <channel id="powerMeteringPowerFactor" typeId="powerMeteringPowerFactor"/>
            <channel id="powerMeteringReportInterval" typeId="powerMeteringReportInterval"/>
            <channel id="powerMeteringMeasurementReset" typeId="powerMeteringMeasurementReset"/>
        </channels>
    </thing-type>

    <!-- Power Metering Channels -->
    <channel-type id="powerMeteringEnergy">
        <item-type>Number</item-type>
        <label>Energy</label>
        <description>Energy since last Reset/Power Up in Watts/Hour.</description>
        <state pattern="%d W/h" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringEnergyAtLastReset">
        <item-type>Number</item-type>
        <label>Energy at last Reset</label>
        <description>Energy at last Reset/Power Up in Watts/Hour.</description>
        <state pattern="%d W/h" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringTimeAtLastReset">
        <item-type>DateTime</item-type>
        <label>Time at last Reset</label>
        <description>Date time of last Reset/Power Up.</description>
        <state readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringInstantaneousPower">
        <item-type>Number</item-type>
        <label>Instantaneous Power</label>
        <description>Present power in Watts.</description>
        <state pattern="%d W" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringAveragePower">
        <item-type>Number</item-type>
        <label>Average Power</label>
        <description>Average power over the period of time specified in Average Power Interval in Watts.</description>
        <state pattern="%d W" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringAveragePowerInterval">
        <item-type>Number</item-type>
        <label>Average Power Interval</label>
        <description>Average Power Interval in Seconds.</description>
        <state pattern="%d s" readOnly="false"/>
    </channel-type>
    <channel-type id="powerMeteringVoltage">
        <item-type>Number</item-type>
        <label>Voltage</label>
        <description>Present Voltage in Volts.</description>
        <state pattern="%d V" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringCurrent">
        <item-type>Number</item-type>
        <label>Current</label>
        <description>Present Current in Amperes.</description>
        <state pattern="%d A" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringFrequency">
        <item-type>Number</item-type>
        <label>Frequency</label>
        <description>Present Frequency in Hertz.</description>
        <state pattern="%d Hz" readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringPowerFactor">
        <item-type>Number</item-type>
        <label>Power Factor</label>
        <description>Ratio between real and apparent power (between zero and one).</description>
        <state readOnly="true"/>
    </channel-type>
    <channel-type id="powerMeteringReportInterval">
        <item-type>Number</item-type>
        <label>Report Interval</label>
        <description>Report Interval in Seconds.</description>
        <state pattern="%d s" readOnly="false"/>
    </channel-type>
    <channel-type id="powerMeteringMeasurementReset">
        <item-type>Switch</item-type>
        <label>Reset Measurements</label>
        <description>Resets the energy value.</description>
        <state readOnly="false"/>
    </channel-type>
</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.ble.bluegiga/ESH-INF/thing/bluegiga.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="ble" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<bridge-type id="bluegiga">
		<label>BlueGiga Bluetooth Interface</label>
		<description>Serial interface to the BlueGiga BLE interface</description>

		<channels>
			<channel id="channel1" typeId="sample-channel" />
		</channels>

		<config-description>
			<parameter name="bluegiga_port" type="text" required="true">
				<label>Port</label>
				<description>Serial Port</description>
			</parameter>
		</config-description>
	</bridge-type>

</thing:thing-descriptions>

=== eclipse-archived/smarthome/extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/ESH-INF/thing/homeassistant-thing.xml
<?xml version="1.0" encoding="UTF-8"?>
<thing:thing-descriptions bindingId="mqtt"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:thing="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0"
	xsi:schemaLocation="http://eclipse.org/smarthome/schemas/thing-description/v1.0.0 http://eclipse.org/smarthome/schemas/thing-description-1.0.0.xsd">

	<thing-type id="homeassistant">
		<supported-bridge-type-refs>
			<bridge-type-ref id="broker" />
			<bridge-type-ref id="systemBroker" />
		</supported-bridge-type-refs>
		<label>HomeAssistant MQTT Component</label>
		<description>You need a configured Broker first. This Thing represents a device, that follows the "HomeAssistant MQTT Component" specification.</description>
		<config-description>
			<parameter name="objectid" type="text" required="true">
				<label>Object ID</label>
				<description>HomeAssistant Object ID</description>
			</parameter>

			<parameter name="basetopic" type="text" required="true">
				<label>MQTT base prefix</label>
				<description>MQTT base prefix</description>
				<default>homeassistant</default>
			</parameter>
		</config-description>
	</thing-type>
</thing:thing-descriptions>
